In [1]:
import numpy as np
import pandas as pd

# **Parte 1**

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
def matriz(m):
  df = pd.read_csv(m, header=None)
  return df.values

# Vecindad derecha
def vder(matriz1, nodo):
    return [j for j in range(len(matriz1)) if matriz1[nodo][j] == 1]

# Vecindad izquierda
def vizq(matriz1, nodo):
    return [i for i in range(len(matriz1)) if matriz1[i][nodo] == 1]

# Minimales
def mini(matriz1):
    return [j for j in range(len(matriz1)) if all(matriz1[i][j] == 0 for i in range(len(matriz1)))]

# Maximales
def maxi(matriz1):
    return [i for i in range(len(matriz1)) if all(matriz1[i][j] == 0 for j in range(len(matriz1)))]

matriz1 = matriz('01.csv')
print(matriz1)
print("Minimales:", mini(matriz1))
print("Maximales:", maxi(matriz1))
print("Vecindad derecha del nodo 0:", vder(matriz1, 0))
print("Vecindad izquierda del nodo 1:", vizq(matriz1, 1))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
Minimales: []
Maximales: []
Vecindad derecha del nodo 0: [0]
Vecindad izquierda del nodo 1: [1]


In [ ]:
def matriz(m):
  df = pd.read_csv(m, header=None)
  return df.values

# Vecindad derecha
def vder(matriz1, nodo):
    return [j for j in range(len(matriz1)) if matriz1[nodo][j] == 1]

# Vecindad izquierda
def vizq(matriz1, nodo):
    return [i for i in range(len(matriz1)) if matriz1[i][nodo] == 1]

# Minimales
def mini(matriz1):
    return [j for j in range(len(matriz1)) if all(matriz1[i][j] == 0 for i in range(len(matriz1)))]

# Maximales
def maxi(matriz1):
    return [i for i in range(len(matriz1)) if all(matriz1[i][j] == 0 for j in range(len(matriz1)))]

matriz1 = matriz('02.csv')
print(matriz1)
print("Minimales:", mini(matriz1))
print("Maximales:", maxi(matriz1))
print("Vecindad derecha del nodo 0:", vder(matriz1, 0))
print("Vecindad izquierda del nodo 1:", vizq(matriz1, 1))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
Minimales: [4, 5]
Maximales: [0]
Vecindad derecha del nodo 0: []
Vecindad izquierda del nodo 1: [1]


In [ ]:
def matriz(m):
  df = pd.read_csv(m, header=None)
  return df.values

# Vecindad derecha
def vder(matriz1, nodo):
    return [j for j in range(len(matriz1)) if matriz1[nodo][j] == 1]

# Vecindad izquierda
def vizq(matriz1, nodo):
    return [i for i in range(len(matriz1)) if matriz1[i][nodo] == 1]

# Minimales
def mini(matriz1):
    return [j for j in range(len(matriz1)) if all(matriz1[i][j] == 0 for i in range(len(matriz1)))]

# Maximales
def maxi(matriz1):
    return [i for i in range(len(matriz1)) if all(matriz1[i][j] == 0 for j in range(len(matriz1)))]

matriz1 = matriz('03.csv')
print(matriz1)
print("Minimales:", mini(matriz1))
print("Maximales:", maxi(matriz1))
print("Vecindad derecha del nodo 0:", vder(matriz1, 0))
print("Vecindad izquierda del nodo 1:", vizq(matriz1, 1))

[[0 0 0 0 0 1]
 [0 1 1 0 0 0]
 [0 1 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]]
Minimales: [4]
Maximales: [4]
Vecindad derecha del nodo 0: [5]
Vecindad izquierda del nodo 1: [1, 2]


In [ ]:
def matriz(m):
  df = pd.read_csv(m, header=None)
  return df.values

# Vecindad derecha
def vder(matriz1, nodo):
    return [j for j in range(len(matriz1)) if matriz1[nodo][j] == 1]

# Vecindad izquierda
def vizq(matriz1, nodo):
    return [i for i in range(len(matriz1)) if matriz1[i][nodo] == 1]

# Minimales
def mini(matriz1):
    return [j for j in range(len(matriz1)) if all(matriz1[i][j] == 0 for i in range(len(matriz1)))]

# Maximales
def maxi(matriz1):
    return [i for i in range(len(matriz1)) if all(matriz1[i][j] == 0 for j in range(len(matriz1)))]

matriz1 = matriz('04.csv')
print(matriz1)
print("Minimales:", mini(matriz1))
print("Maximales:", maxi(matriz1))
print("Vecindad derecha del nodo 0:", vder(matriz1, 0))
print("Vecindad izquierda del nodo 1:", vizq(matriz1, 1))

[[0 0 1 0 0 1]
 [1 1 1 0 0 0]
 [0 1 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]]
Minimales: [4]
Maximales: [4]
Vecindad derecha del nodo 0: [2, 5]
Vecindad izquierda del nodo 1: [1, 2]


# **Parte 2**

In [3]:
from google.colab import files
uploaded = files.upload()


Saving 01.json to 01.json
Saving 02.json to 02.json
Saving 03.json to 03.json


In [9]:
import json

def grafojson(archie):
    with open(archie, 'r') as f:
        estructura = json.load(f)
    return estructura['E']

def es_reflexivo(grafo):
    return all(nodo in vecinos for nodo, vecinos in grafo.items())

def es_simetrico(grafo):
    for nodo, vecinos in grafo.items():
        for vecino in vecinos:
            if nodo not in grafo.get(vecino, []):
                return False
    return True

def es_antisimetrico(grafo):
    for nodo, vecinos in grafo.items():
        for vecino in vecinos:
            if vecino != nodo and nodo in grafo.get(vecino, []):
                return False
    return True

def es_transitivo(grafo):
    for a, vecinos_a in grafo.items():
        for b in vecinos_a:
            vecinos_b = grafo.get(b, [])
            for c in vecinos_b:
                if c not in grafo[a]:
                    return False
    return True

grafo = grafojson("01.json")
print("Reflexivo:", es_reflexivo(grafo))
print("Simétrico:", es_simetrico(grafo))
print("Antisimétrico:", es_antisimetrico(grafo))
print("Transitivo:", es_transitivo(grafo))

if es_reflexivo(grafo) and es_simetrico(grafo) and es_transitivo(grafo):
    print("Es una relación de equivalencia")
elif es_reflexivo(grafo) and es_antisimetrico(grafo) and es_transitivo(grafo):
    print("Es un orden parcial")
else:
    print("No es ni orden ni equivalencia")


Reflexivo: True
Simétrico: False
Antisimétrico: True
Transitivo: True
Es un orden parcial


In [5]:
def grafojson(archie):
    with open(archie, 'r') as f:
        estructura = json.load(f)
    return estructura['E']  # Diccionario de adyacencia


def es_reflexivo(grafo):
    return all(nodo in vecinos for nodo, vecinos in grafo.items())

def es_simetrico(grafo):
    for nodo, vecinos in grafo.items():
        for vecino in vecinos:
            if nodo not in grafo.get(vecino, []):
                return False
    return True

def es_antisimetrico(grafo):
    for nodo, vecinos in grafo.items():
        for vecino in vecinos:
            if vecino != nodo and nodo in grafo.get(vecino, []):
                return False
    return True

def es_transitivo(grafo):
    for a, vecinos_a in grafo.items():
        for b in vecinos_a:
            vecinos_b = grafo.get(b, [])
            for c in vecinos_b:
                if c not in grafo[a]:
                    return False
    return True

grafo = grafojson("02.json")
print("Reflexivo:", es_reflexivo(grafo))
print("Simétrico:", es_simetrico(grafo))
print("Antisimétrico:", es_antisimetrico(grafo))
print("Transitivo:", es_transitivo(grafo))

if es_reflexivo(grafo) and es_simetrico(grafo) and es_transitivo(grafo):
    print("Es una relación de equivalencia")
elif es_reflexivo(grafo) and es_antisimetrico(grafo) and es_transitivo(grafo):
    print("Es un orden parcial")
else:
    print("No es ni orden ni equivalencia")

Reflexivo: True
Simétrico: False
Antisimétrico: False
Transitivo: False
No es ni orden ni equivalencia


In [10]:
def grafojson(archie):
    with open(archie, 'r') as f:
        estructura = json.load(f)
    return estructura['E']  # Diccionario de adyacencia


def es_reflexivo(grafo):
    return all(nodo in vecinos for nodo, vecinos in grafo.items())

def es_simetrico(grafo):
    for nodo, vecinos in grafo.items():
        for vecino in vecinos:
            if nodo not in grafo.get(vecino, []):
                return False
    return True

def es_antisimetrico(grafo):
    for nodo, vecinos in grafo.items():
        for vecino in vecinos:
            if vecino != nodo and nodo in grafo.get(vecino, []):
                return False
    return True

def es_transitivo(grafo):
    for a, vecinos_a in grafo.items():
        for b in vecinos_a:
            vecinos_b = grafo.get(b, [])
            for c in vecinos_b:
                if c not in grafo[a]:
                    return False
    return True

grafo = grafojson("03.json")
print("Reflexivo:", es_reflexivo(grafo))
print("Simétrico:", es_simetrico(grafo))
print("Antisimétrico:", es_antisimetrico(grafo))
print("Transitivo:", es_transitivo(grafo))

if es_reflexivo(grafo) and es_simetrico(grafo) and es_transitivo(grafo):
    print("Es una relación de equivalencia")
elif es_reflexivo(grafo) and es_antisimetrico(grafo) and es_transitivo(grafo):
    print("Es un orden parcial")
else:
    print("No es ni orden ni equivalencia")

Reflexivo: True
Simétrico: False
Antisimétrico: False
Transitivo: False
No es ni orden ni equivalencia


# **Parte 3**

In [1]:
from google.colab import files
uploaded = files.upload()

Saving esDivisorDe-200.json to esDivisorDe-200.json
Saving esDivisorDe-2000.json to esDivisorDe-2000.json
Saving esDivisorDe-20000.json to esDivisorDe-20000.json
Saving multiplos200Ref.json to multiplos200Ref.json
Saving multiplos2000Ref.json to multiplos2000Ref.json
Saving multiplos20000Ref.json to multiplos20000Ref.json


In [8]:
import json

def grafojson(prueba):
    with open(prueba, 'r') as f:
        estructura = json.load(f)
    return estructura["E"]

grafo = grafojson("multiplos200Ref.json")
print("Nodos:", list(grafo.keys()))


#Hice esto solo para ver los nodos que hay en cada archivo.#

Nodos en el grafo: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', '155', '15

Por otro lado, lo que es el archivo "esDivisorDe-20000.json" y "multiplos20000Ref.json", no me funcionan, sale error.

In [32]:
import json
from collections import deque

def grafojson(exo):
    with open(exo, 'r') as f:
        estructura = json.load(f)
    return estructura["E"]

def camino1(grafo, inicio, destino):
    visitados = set()
    cola = deque([[inicio]])

    while cola:
        camino = cola.popleft()
        nodo_actual = camino[-1]

        if nodo_actual == destino:
            return camino

        if nodo_actual not in visitados:
            visitados.add(nodo_actual)
            for vecino in grafo.get(nodo_actual, []):
                nuevo_camino = list(camino)
                nuevo_camino.append(vecino)
                cola.append(nuevo_camino)

    return None  # Si no se encuentro camino

grafo = grafojson("esDivisorDe-200.json")

# Obtener primer y último nodo
nodos = list(grafo.keys())
inicio = nodos[0]
destino = nodos[-1]

print("Nodo inicial: ", inicio)
print("Nodo final: ", destino)

camino = camino1(grafo, inicio, destino)

if camino:
    print("Camino encontrado:", " a ".join(camino))
else:
    print("No existe camino entre ", inicio, "y", destino)


Nodo inicial:  1
Nodo final:  99
Camino encontrado: 1 a 99


Todos 4 archivos json tienen el mismo resultado, se les encuentra el camino del primero al ultimo nodo.
Por eso no repetí acá el código.

Nos dio curiosidad para ver cuales eran realmente los caminos entre nodos que permiten la conexión, para eso hicimos lo siguiente:


In [49]:
def grafojson(prueba1):
    with open(prueba1, 'r') as f:
        estructura = json.load(f)
    return estructura["E"]

def encontrarcaminos(grafo, nodo1):
    predecesores = []
    for nodo, vecinos in grafo.items():
        if nodo1 in vecinos:
            predecesores.append(nodo)
    return predecesores

grafo = grafojson("esDivisorDe-2000.json")
nodo_final = "999" #acá puedo colocar cualquier nodo, y ver sus conexión con otros

#encontrar todos los nodos
conex = encontrarcaminos(grafo, nodo_final)

print(f"Nodos que están conectados a {nodo_final}:")
print(conex)

Nodos que están conectados a 999:
['1', '3', '9', '27', '37', '111', '333']
